# .github/workflows/update.yml
name: Scheduled Spotify Snapshot

on:
  schedule:
    # Every 5 minutes
    - cron:  '*/5 * * * *'
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # so we can push back

      - name: Use Node.js 18
        uses: actions/setup-node@v5
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run snapshot updater
        run: node update.js
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Push changes (if any)
        if: ${{ always() }}
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
